#!/usr/bin/env python3
"""LONGER PERMUTATION CYCLES in the forwarder-thunk map rows (lane CJ-2).

WHAT LANE CI-2 LEFT, VERBATIM
-----------------------------
    "150 rows had a fitting existing name but only 4 were mutual, so the rest
     are ONE-DIRECTIONAL, meaning the correct name is IN USE ELSEWHERE => these
     are LONGER PERMUTATION CYCLES, not swaps. That is the obvious next lane."

CI-2 repaired 2 two-cycles (CharIKHead Load<->SetType, TrackPanelDir
Save<->Copy) and stopped.  This tool measures the cycle structure of the whole
population and extracts the repairs that fall out of it.

THE RELATION IS AT **METHOD** GRANULARITY, NOT MANGLED-NAME GRANULARITY
-----------------------------------------------------------------------
The first reconstruction attempted here matched WHOLE SYNTHESISED NAMES -- for
row A, find a map name N with synth(N) == A's dethunk target row.  It found
139 fitting names and **ZERO** mutual pairs on the pre-CI-2 map, i.e. it could
not reproduce CI-2's own two landed repairs.  The reason is instructive and is
the ICF-fold confound rtti_vtable_index documents:

    0x823c10a8  claims ?Load@CharIKHead@@$4...
                branches to ?SetType@**FlowTrigger**@@UAAXVSymbol@@@Z
    0x823c10f8  claims ?SetType@CharIKHead@@$4...
                branches to ?Load@CharIKHead@@UAAXAAVBinStream@@@Z

The pair is mutual in METHOD (Load <-> SetType) but NOT in mangled name: the
body A forwards to is an ICF fold representative the map names after a
DIFFERENT class (FlowTrigger).  A whole-name relation therefore cannot see the
very swap CI-2 landed.  CI-2's slot channel says the same thing from the other
side -- it "names the correct METHOD but a full mangled signature cannot be
synthesised".  So: match on sig_strict()[0], the method.

The second confirmation that class is the wrong key: CI-2's other landed pair is
?Save@TrackPanelDir**Base**@@ <-> ?Copy@TrackPanelDir@@ -- mutual in method with
the CLASSES DIFFERENT.  The gate that admits it is the home UNIT, not the class.

THE MODEL
---------
Within one pinned unit U, the thunk names are a bag of labels sitting on a bag
of addresses.  For row A let

    h(A) = method claimed by the name currently on A
    w(A) = method of the body A actually branches to  (branch channel)

A is correct iff h(A) == w(A).  A repair permutes the labels inside U so that
every row's h becomes its w.  Define the functional graph

    A -> B   iff B is the UNIQUE row in U with h(B) == w(A)

("B is holding the name A should have").  Then:

  * an AGREE row has h == w, so it maps to ITSELF -- a self-loop.  This is a
    structural safety property, not an assumption: under the uniqueness gate a
    correctly-named row can NEVER be dragged into a multi-row cycle, so no
    rotation this tool proposes can break a currently-correct row.
  * a cycle of length k >= 2 is a k-way rotation that repairs all k rows at once.
  * a node with no candidate, or with >= 2 candidates, is a BLOCKED chain end.

CONTROLS (each stated with the number that would have shown it failing)
----------------------------------------------------------------------
C1 POSITIVE, KNOWN ANSWER.  On the PRE-CI-2 map (481ecc8f^) the two pairs CI-2
   actually landed must come out as 2-cycles.  A relation that cannot reproduce
   an already-landed repair is not measuring the same thing.
C2 SELF-LOOP FLOOR.  The AGREE population is the false-positive floor: those
   rows are known-good, so the relation must return the row ITSELF.  A relation
   that scatters AGREE rows into foreign cycles is noise.
C3 FAIL ON DEMAND.  Shuffle the thunk names WITHIN each unit (the exact swap
   objdiff cannot see -- report.rs:394 masks reloc args) and the self-loop rate
   must COLLAPSE.  If it does not, the relation is fitting noise.
C4 ADJUSTMENT GATE (independent second channel, CF-8).  A rotation moves a name
   onto a new address; the name's `$4PPPPPPPM@<adj>@` field must equal that
   address's own `addi`-derived adjustment.  The branch channel is structurally
   blind to displacement, so this is genuinely independent of how the cycle was
   found.
C5 RTTI VERIFICATION.  Candidates here are generated by the BRANCH channel, so
   the independent verifier is the RTTI oracle (ancestry + vtable-family slot
   consensus).  This is the exact REVERSE of CI-2, which generated with RTTI and
   verified with branch.  Using the generating instrument to verify is circular
   and is not done here.

WHAT THIS TOOL DOES NOT DO
--------------------------
It never proposes a CROSS-UNIT move.  objdiff pairs target<->base by name
WITHIN a unit (CH-3 measured -4 from 9 cross-unit moves), so a name that is
right by retail bytes and wrong by unit LOSES matches.  Every rotation here is
a permutation of labels already inside one pinned unit, which is metric-neutral
by construction on the unit membership axis.

It never SYNTHESISES a name.  Rows whose wanted method is claimed by no row in
their unit are reported as blocked, with the reason, and left alone.
"""
import argparse
import collections
import json
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, '..'))

from thunk_identity import (Image, code_population, adjudicate_strict,       # noqa: E402
                            sig_strict, _adjustment_from_code,
                            _adjustment_from_name)
from homeunit_pins import parse_splits, splits_base, Pins                    # noqa: E402

BAND = os.path.join(ROOT, 'orig/45410914/band.exe')
MAP = os.path.join(ROOT, 'scripts/target_symbol_map.json')
SPLITS = os.path.join(ROOT, 'config/45410914/splits.txt')


# ---------------------------------------------------------------------------
# population + relation
# ---------------------------------------------------------------------------
def build(mappath, exe=BAND, splits=SPLITS):
    """-> (tmap, img, pins, rows) where rows[addr] = adjudication record."""
    tmap = json.load(open(mappath))
    img = Image(exe)
    pins = Pins(splits_base(parse_splits(splits)))
    pop = code_population(img, tmap)
    rows = {}
    for a, n in sorted(pop.items()):
        r = adjudicate_strict(img, tmap, a, n)
        va = int(a, 16)
        r['unit'] = pins.owner(va)
        r['adj_code'] = _adjustment_from_code(img, va)
        r['adj_name'] = _adjustment_from_name(n)
        cs = sig_strict(n)
        r['h'] = cs[0] if cs else None                      # claimed method
        ts = sig_strict(r.get('target_row')) if r.get('target_row') else None
        r['w'] = ts[0] if ts else None                      # wanted method
        rows[a] = r
    return tmap, img, pins, rows


def edges(rows, names, unit_gate=True):
    """A -> B iff B is the UNIQUE row in A's unit claiming A's wanted method.

    Returns (edge, why) where why[A] explains a missing edge.
    """
    by_unit = collections.defaultdict(list)
    for a, r in rows.items():
        by_unit[r['unit']].append(a)
    # method -> addrs, per unit (or globally when the gate is off)
    idx = collections.defaultdict(lambda: collections.defaultdict(list))
    for a, r in rows.items():
        key = r['unit'] if unit_gate else '*'
        if r['h']:
            idx[key][r['h']].append(a)

    edge, why = {}, {}
    for a, r in rows.items():
        if r['w'] is None:
            why[a] = 'no-wanted-method(%s)' % r['verdict']
            continue
        key = r['unit'] if unit_gate else '*'
        if unit_gate and r['unit'] is None:
            why[a] = 'unpinned'
            continue
        cands = idx[key].get(r['w'], [])
        if not cands:
            why[a] = 'wanted-method-absent-from-unit'
        elif len(cands) > 1:
            why[a] = 'ambiguous(%d holders)' % len(cands)
        else:
            edge[a] = cands[0]
    return edge, why


def cycles(edge):
    """Cycle decomposition of a partial functional graph."""
    colour, out = {}, []
    for start in edge:
        if start in colour:
            continue
        path, node = [], start
        while node is not None and node not in colour:
            colour[node] = 'grey'
            path.append(node)
            node = edge.get(node)
        if node is not None and colour.get(node) == 'grey':
            out.append(path[path.index(node):])
        for n in path:
            colour[n] = 'black'
    return out


# ---------------------------------------------------------------------------
# controls
# ---------------------------------------------------------------------------
def selfloop_rate(rows, edge, verdict='AGREE'):
    sel = [a for a, r in rows.items() if r['verdict'] == verdict]
    if not sel:
        return 0.0, 0, 0
    hit = sum(1 for a in sel if edge.get(a) == a)
    return 100.0 * hit / len(sel), hit, len(sel)


def shuffled_rows(rows, seed):
    """C3: permute the NAMES within each unit, recompute h (w is retail-derived
    and must NOT move -- it comes from the binary, not the map)."""
    rnd = random.Random(seed)
    by_unit = collections.defaultdict(list)
    for a, r in rows.items():
        by_unit[r['unit']].append(a)
    out = {a: dict(r) for a, r in rows.items()}
    for _u, addrs in by_unit.items():
        hs = [rows[a]['h'] for a in addrs]
        rnd.shuffle(hs)
        for a, h in zip(addrs, hs):
            out[a]['h'] = h
    return out


# ---------------------------------------------------------------------------
# report
# ---------------------------------------------------------------------------
def describe(rows, cyc, tmap):
    """Render one cycle as the rotation it proposes."""
    out = []
    for c in cyc:
        item = {'len': len(c), 'unit': rows[c[0]]['unit'], 'rows': []}
        for a in c:
            b = None
            for i, x in enumerate(c):
                if x == a:
                    b = c[(i + 1) % len(c)]
            item['rows'].append({
                'addr': a, 'old': tmap[a], 'new': tmap[b],
                'verdict': rows[a]['verdict'],
                'h': rows[a]['h'], 'w': rows[a]['w'],
                'adj_code': rows[a]['adj_code'],
                'adj_name_new': _adjustment_from_name(tmap[b]),
                'target': rows[a].get('target'),
                'target_row': rows[a].get('target_row'),
            })
        item['adj_ok'] = all(r['adj_code'] == r['adj_name_new'] for r in item['rows'])
        item['all_defective'] = all(r['verdict'] == 'METHOD_DIFFERS' for r in item['rows'])
        out.append(item)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--map', default=MAP)
    ap.add_argument('--exe', default=BAND)
    ap.add_argument('--no-unit-gate', action='store_true',
                    help='measure what the home-unit gate costs (NOT for landing)')
    ap.add_argument('--json', help='write cycle records here')
    ap.add_argument('--quiet-controls', action='store_true')
    args = ap.parse_args()

    tmap, img, pins, rows = build(args.map, args.exe)
    v = collections.Counter(r['verdict'] for r in rows.values())
    print('map %s' % args.map)
    print('thunk code population %d   %s' % (len(rows), dict(v)))
    unp = sum(1 for r in rows.values() if r['unit'] is None)
    print('unpinned rows (no home unit): %d / %d' % (unp, len(rows)))

    edge, why = edges(rows, tmap, unit_gate=not args.no_unit_gate)
    print('edges resolved: %d   unresolved: %d' % (len(edge), len(why)))
    print('  unresolved reasons: %s'
          % dict(collections.Counter(w.split('(')[0] for w in why.values())))

    if not args.quiet_controls:
        r2, hit, n = selfloop_rate(rows, edge, 'AGREE')
        print('\n[C2] SELF-LOOP FLOOR   AGREE rows mapping to THEMSELVES: '
              '%d/%d = %.1f%%' % (hit, n, r2))
        for seed in (3, 11, 29):
            sh = shuffled_rows(rows, seed)
            e2, _ = edges(sh, tmap, unit_gate=not args.no_unit_gate)
            rs, h2, n2 = selfloop_rate(rows, e2, 'AGREE')
            print('[C3] fail-on-demand  within-unit name shuffle seed %-3d -> '
                  '%d/%d = %.1f%%' % (seed, h2, n2, rs))

    cyc = [c for c in cycles(edge) if len(c) >= 2]
    dist = collections.Counter(len(c) for c in cyc)
    md = [a for a, r in rows.items() if r['verdict'] == 'METHOD_DIFFERS']
    print('\n=== CYCLE-LENGTH DISTRIBUTION (denominator: %d METHOD_DIFFERS rows '
          'of %d thunk rows) ===' % (len(md), len(rows)))
    tot = 0
    for k in sorted(dist):
        print('  length %-3d : %-4d cycles  (%d rows)' % (k, dist[k], k * dist[k]))
        tot += k * dist[k]
    print('  TOTAL      : %d cycles covering %d rows = %.1f%% of METHOD_DIFFERS'
          % (len(cyc), tot, 100.0 * tot / max(len(md), 1)))
    print('  self-loops (rows already consistent): %d'
          % sum(1 for a in edge if edge[a] == a))

    recs = describe(rows, cyc, tmap)
    ok = [r for r in recs if r['adj_ok'] and r['all_defective']]
    print('\n  cycles passing the ADJUSTMENT gate [C4] and all-defective: %d / %d'
          % (len(ok), len(recs)))
    for r in recs:
        flag = 'OK ' if (r['adj_ok'] and r['all_defective']) else 'REJ'
        print('  [%s] len=%d unit=%s adj_ok=%s all_defective=%s'
              % (flag, r['len'], r['unit'], r['adj_ok'], r['all_defective']))
        for x in r['rows']:
            print('        %s  %-58s -> %-58s' % (x['addr'], x['old'][:58], x['new'][:58]))

    # --- blocked chains: where does an unresolved row's chain die? -----------
    print('\n=== BLOCKERS on METHOD_DIFFERS rows (why no cycle) ===')
    bl = collections.Counter()
    for a in md:
        if a in edge:
            continue
        bl[why.get(a, 'unknown').split('(')[0]] += 1
    incyc = {a for c in cyc for a in c}
    bl['in-a-cycle(repairable)'] = len([a for a in md if a in incyc])
    bl['edge-but-not-in-cycle(open chain)'] = len(
        [a for a in md if a in edge and a not in incyc])
    for k, n in bl.most_common():
        print('  %-42s %d' % (k, n))

    if args.json:
        json.dump({'cycles': recs, 'blockers': dict(bl),
                   'population': len(rows), 'method_differs': len(md)},
                  open(args.json, 'w'), indent=1)
        print('\nwrote %s' % args.json)
    return 0


if __name__ == '__main__':
    sys.exit(main())


# ---------------------------------------------------------------------------
# PER-UNIT MULTISET BALANCE -- the gate-free structural test
# ---------------------------------------------------------------------------
# The functional-graph view above needs a UNIQUENESS gate, and uniqueness is
# exactly where a longer cycle would hide: if two rows in a unit both claim
# `Copy`, every chain through `Copy` reads "ambiguous" and the cycle is
# suppressed by the instrument rather than by the data.  Reporting "no long
# cycles" on that basis would be a manufactured decisive negative.
#
# The gate-free statement is a MULTISET identity.  Inside unit U let D be the
# defective (METHOD_DIFFERS) rows.  Write
#       W = multiset{ w(A) : A in D }   the methods those rows SHOULD claim
#       H = multiset{ h(A) : A in D }   the methods those rows DO claim
# If W == H the defects are a CLOSED PERMUTATION of D: every needed name is
# already inside D, so a rotation exists that repairs all of them and touches
# nothing else.  If W != H the surplus of W over H is the set of names that must
# come from OUTSIDE D -- from a correctly-named (AGREE) row, which a rotation
# would BREAK, or from a name that does not exist in the unit at all and would
# have to be SYNTHESISED.  That surplus is the concrete blocker, and it is
# measured here rather than assumed.
def unit_balance(rows, adj_disambiguate=True):
    by_unit = collections.defaultdict(list)
    for a, r in rows.items():
        by_unit[r['unit']].append(a)

    report = []
    for u, addrs in sorted(by_unit.items(), key=lambda kv: str(kv[0])):
        D = [a for a in addrs if rows[a]['verdict'] == 'METHOD_DIFFERS']
        if not D:
            continue
        W = collections.Counter(rows[a]['w'] for a in D)
        H = collections.Counter(rows[a]['h'] for a in D)
        surplus = W - H          # wanted but not held inside D
        deficit = H - W          # held inside D but not wanted by it
        item = {'unit': u, 'n_defective': len(D), 'balanced': (surplus == deficit == collections.Counter()),
                'surplus': dict(surplus), 'deficit': dict(deficit), 'cycles': []}
        if item['balanced']:
            item['cycles'] = _match_cycles(rows, D, adj_disambiguate)
        report.append(item)
    return report


def _match_cycles(rows, D, adj_disambiguate):
    """D is multiset-balanced: build a permutation and decompose it."""
    holders = collections.defaultdict(list)
    for a in D:
        holders[rows[a]['h']].append(a)
    perm, ambiguous = {}, 0
    used = set()
    for a in D:
        cands = [b for b in holders[rows[a]['w']] if b not in used]
        if len(cands) > 1 and adj_disambiguate:
            f = [b for b in cands if rows[b]['adj_name'] == rows[a]['adj_code']]
            if len(f) == 1:
                cands = f
        if not cands:
            return []                      # should not happen when balanced
        if len(cands) > 1:
            ambiguous += 1
        perm[a] = cands[0]
        used.add(cands[0])
    out = []
    seen = set()
    for a in D:
        if a in seen:
            continue
        c, n = [], a
        while n not in seen:
            seen.add(n)
            c.append(n)
            n = perm[n]
        if n == a and len(c) >= 2:
            out.append({'cycle': c, 'ambiguous_steps': ambiguous})
        elif n == a and len(c) == 1:
            pass
    return out


# ---------------------------------------------------------------------------
# THE CORRECT MODEL: simple cycles in the per-unit DEFECTIVE-ONLY digraph
# ---------------------------------------------------------------------------
# Two earlier formulations in this file are both special cases and both mislead
# if used alone:
#   * the FUNCTIONAL graph needs a uniqueness gate, and a unit with two rows
#     claiming the same method makes every chain through that method read
#     "ambiguous" -- suppressing cycles by instrument rather than by data;
#   * the WHOLE-UNIT multiset balance is too coarse -- a unit holding one closed
#     2-cycle plus one unrelated defective row fails it, and the 52 units with
#     exactly ONE defective row can never balance by construction.
#
# The general statement: inside a unit, over the DEFECTIVE rows only, draw
# A -> B iff h(B) == w(A).  Every SIMPLE CYCLE is a valid rotation, and because
# the vertex set excludes correctly-named rows, no rotation can ever break one.
# Units are small (max 8 defective rows here), so simple cycles are enumerated
# exhaustively -- this is exact, not a heuristic search.
def unit_digraph_cycles(rows, max_len=12):
    by_unit = collections.defaultdict(list)
    for a, r in rows.items():
        by_unit[r['unit']].append(a)
    found = []
    for u, addrs in sorted(by_unit.items(), key=lambda kv: str(kv[0])):
        D = [a for a in addrs if rows[a]['verdict'] == 'METHOD_DIFFERS']
        if len(D) < 2:
            continue
        adjm = {a: [b for b in D if b != a and rows[b]['h'] == rows[a]['w']]
                for a in D}
        # exhaustive simple-cycle enumeration, canonicalised on the smallest
        # vertex so each cycle is reported exactly once
        seen = set()

        def walk(start, node, path):
            for nxt in adjm[node]:
                if nxt == start and len(path) >= 2:
                    key = tuple(path)
                    rot = min(range(len(path)), key=lambda i: path[i])
                    key = tuple(path[rot:] + path[:rot])
                    if key not in seen:
                        seen.add(key)
                        found.append({'unit': u, 'len': len(path),
                                      'cycle': list(key)})
                elif nxt not in path and nxt > start and len(path) < max_len:
                    walk(start, nxt, path + [nxt])

        for a in sorted(D):
            walk(a, a, [a])
    return found
