"""gdb-attach: generate GDB scripts for debugging c2.dll under wibo.

Generates a .gdb script that:
- Loads wibo with debug symbols
- Sets 32-bit architecture for PE code
- Maps c2.dll address space
- Sets hardware breakpoints at addresses from c2_funcmap.json
- Provides convenience commands (pe-regs, bt32)
"""

import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

from .invoker import (
    CompilerInvoker,
    PROJECT_ROOT,
    WIBO,
    C2_DLL,
    C2_IMAGE_BASE,
    C2_TEXT_START,
    C2_TEXT_END,
)
from .funcmap import C2FuncMap, DEFAULT_FUNCMAP_PATH
from .rr_record import _find_rr, CUSTOM_RR_LIB


# Wibo source location (for source-level debugging)
WIBO_SOURCE = Path.home() / "code" / "wibo"


def generate_gdb_script(
    funcmap: C2FuncMap,
    min_evidence: int = 2,
    rr_trace: Optional[Path] = None,
) -> str:
    """Generate a GDB initialization script for c2.dll debugging."""
    lines = []
    lines.append("# Auto-generated GDB script for c2.dll debugging")
    lines.append("# Generated by: python -m tools.compiler_trace gdb-attach")
    lines.append("")

    if rr_trace:
        # rr replay mode: connect to rr's gdbserver
        lines.append(f"# rr replay mode")
        lines.append(f"set architecture i386")
        lines.append(f"file {WIBO}")
        lines.append(f"target extended-remote :0")
        lines.append("")
    else:
        # Live debugging mode
        lines.append(f"file {WIBO}")
        lines.append("")

    # Wibo source directory
    if WIBO_SOURCE.exists():
        lines.append(f"directory {WIBO_SOURCE}")
        lines.append("")

    # c2.dll info
    lines.append(f"# c2.dll: ImageBase=0x{C2_IMAGE_BASE:08x}")
    lines.append(f"# c2.dll .text: 0x{C2_TEXT_START:08x} - 0x{C2_TEXT_END:08x}")
    lines.append("")

    # Convenience commands
    lines.append("# --- Convenience commands ---")
    lines.append("")

    # pe-regs: dump registers relevant to PE/x86-32 calling convention
    lines.append("define pe-regs")
    lines.append('  printf "eax=0x%08x ebx=0x%08x ecx=0x%08x edx=0x%08x\\n", $eax, $ebx, $ecx, $edx')
    lines.append('  printf "esi=0x%08x edi=0x%08x ebp=0x%08x esp=0x%08x\\n", $esi, $edi, $ebp, $esp')
    lines.append('  printf "eip=0x%08x eflags=0x%08x\\n", $eip, $eflags')
    lines.append("end")
    lines.append('document pe-regs')
    lines.append('  Show x86-32 PE register state')
    lines.append('end')
    lines.append("")

    # bt32: manual frame-pointer backtrace for 32-bit PE code
    lines.append("define bt32")
    lines.append("  set $fp = $ebp")
    lines.append("  set $depth = 0")
    lines.append('  printf "Manual backtrace (EBP chain):\\n"')
    lines.append("  while $fp != 0 && $depth < 20")
    lines.append("    set $ret = *(unsigned int*)($fp + 4)")
    lines.append('    printf "  #%d: EBP=0x%08x RET=0x%08x", $depth, $fp, $ret')
    lines.append(f'    if $ret >= 0x{C2_TEXT_START:08x} && $ret < 0x{C2_TEXT_END:08x}')
    lines.append(f'      printf " [c2.dll +0x%x]", $ret - 0x{C2_IMAGE_BASE:08x}')
    lines.append("    end")
    lines.append('    printf "\\n"')
    lines.append("    set $fp = *(unsigned int*)$fp")
    lines.append("    set $depth = $depth + 1")
    lines.append("  end")
    lines.append("end")
    lines.append('document bt32')
    lines.append('  Manual EBP-chain backtrace for 32-bit PE code (c2.dll)')
    lines.append('end')
    lines.append("")

    # c2-addr: convert c2.dll RVA to VA
    lines.append("define c2-addr")
    lines.append(f'  printf "c2.dll VA: 0x%08x (RVA 0x%x)\\n", $arg0 + 0x{C2_IMAGE_BASE:08x}, $arg0')
    lines.append("end")
    lines.append('document c2-addr')
    lines.append('  Convert c2.dll RVA to virtual address')
    lines.append('end')
    lines.append("")

    # Breakpoints from funcmap
    bps = funcmap.get_breakpoints(min_evidence)
    if bps:
        lines.append(f"# --- Breakpoints from c2_funcmap.json ({len(bps)} addresses, min_evidence={min_evidence}) ---")
        lines.append("")
        for va, entry in bps:
            obs_count = len(entry["observations"])
            label = entry.get("label", "")
            rva = entry["rva"]
            comment = f"# {obs_count} observations"
            if label:
                comment += f", {label}"
            lines.append(f"hbreak *0x{va:08x}  {comment}  (RVA 0x{rva:x})")
        lines.append("")
    else:
        lines.append("# No breakpoints from funcmap (run callgrind-diff first)")
        lines.append("")

    return "\n".join(lines)


def cmd_gdb_attach(args) -> None:
    """Entry point for gdb-attach subcommand."""
    funcmap_path = Path(args.funcmap) if args.funcmap else DEFAULT_FUNCMAP_PATH
    funcmap = C2FuncMap(funcmap_path)

    rr_trace = Path(args.rr_trace) if args.rr_trace else None

    script = generate_gdb_script(
        funcmap,
        min_evidence=args.min_evidence,
        rr_trace=rr_trace,
    )

    if args.print_only:
        print(script)
        return

    # Write script to temp file and launch GDB
    script_path = Path(tempfile.mktemp(suffix=".gdb", prefix="c2_debug_"))
    script_path.write_text(script)

    if rr_trace:
        # Launch rr replay with our GDB script
        rr_bin = _find_rr()
        print(f"GDB script: {script_path}")
        print(f"Launching rr replay (using {rr_bin})...")
        rr_env = None
        if CUSTOM_RR_LIB.exists():
            rr_env = {**os.environ, "LD_LIBRARY_PATH": str(CUSTOM_RR_LIB)}
        subprocess.run(
            [rr_bin, "replay", "-x", str(script_path), str(rr_trace)],
            cwd=PROJECT_ROOT,
            env=rr_env,
        )
    elif args.source:
        # Live debugging: start wibo under GDB
        source = Path(args.source).resolve()
        invoker = CompilerInvoker()
        obj_path = Path(tempfile.mktemp(suffix=".obj", prefix="gdb_compile_"))
        cmd = invoker.base_command(source, obj_path)

        print(f"GDB script: {script_path}")
        print(f"Launching GDB with compilation of {source.name}...")
        gdb_cmd = ["gdb", "-x", str(script_path), "--args"] + cmd
        subprocess.run(gdb_cmd, cwd=PROJECT_ROOT)
    else:
        # Just print the script if no source or rr trace
        print(script)
        print(f"\nScript written to: {script_path}")
        print(f"Use with: gdb -x {script_path} --args <wibo command>")
