#!/usr/bin/env python3
"""CORRECTED local-static census (laneAY, 2026-07-27).

Supersedes scripts/harvest/localstatic_census_wide.py, whose RESOLVER is sound
(18/18 exact string resolution against reference commit 7d5c413e) but whose ROW
SELECTION is not.

★ THE DEFECT (measured, this is the FOURTH census bug in this tool family)
census_wide.py enumerates its universe by GLOBBING `build/45410914/obj/**/*.obj`
and keys each row on the obj's relative path. That directory is **never cleaned**,
so it holds three different kinds of file:

  1.  live target objs   -- 894 units that dtk carves AND we compile
  2.  target-only pins   -- 3,071 units pinned in splits.txt with no compiled
                            source (nothing to edit; their "excess" is trivially
                            the whole target-side count)
  3.  ORPHANS            -- 11,960 `auto_NN_<VA>_text` carves plus **112 STALE
                            objs left behind by earlier splits.txt generations**
                            (e.g. `obj/FxSend.obj` mtime 07-26 22:24, orphaned
                            when the pin was renamed to `system/synth/FxSend.cpp`;
                            likewise `band3/game/VocalPlayer`, `SynthSample`,
                            `FxSendDelay/Chorus/EQ/Distortion`, `Utl`, `Meta`,
                            `Movie`, `band3/bandtrack/GemManager`,
                            `band3/meta_band/UIEventMgr`, ...).

Measured consequence at 39,266: **9,911 of 13,932 reported excess statics (71%)
sat in class 3**, and the TOP of the ranked "ACTIONABLE" list was stale --
`band3/game/VocalPlayer` (46 statics, the single largest row), `FxSend` (12),
`SynthSample` (10), `FxSendDelay` (7) are all orphan carves of a splits geometry
that no longer exists. Ranking by `max(variants)` over same-basename objs
actively PREFERRED the stale obj whenever its carve was wider.

★ THE FIX: enumerate from **objdiff.json**, not from the filesystem.
`objdiff.json` is generated by configure.py from the live objects.json +
splits.txt and carries the authoritative triple per unit:
    name  ==  report.json units[].name   (exact -- no split('/') guessing)
    target_path                          (the live dtk carve)
    base_path                            (present iff we compile the TU)
Anything in obj/ that is not some unit's target_path is BY CONSTRUCTION not
actionable. The orphan set is still counted and named, but as a diagnostic.

★ Why the old `pct` join also mis-fired: report unit names are `default/<stem>`
for 3,789 units but `default/<dir>/<dir>/<stem>` for 176 of them, while the obj
tree is flat for 12,745 and nested for 223 -- and the two nestings do NOT
agree unit-for-unit. `split('/', 1)[-1]` therefore silently missed every
dual-generation pair. Using objdiff.json's own `name` removes the guess.

Usage: python3 scripts/harvest/localstatic_census_v2.py <worktree> [--json out]
"""
import argparse, collections, glob, json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import localstatic_patch_gen as G
from localstatic_census_wide import (LANE_AT_OWNED, LANE_AX_INFLIGHT,
                                     ANONNS_RE, STL_RE, ANON_RE, norm)


def load_units(wt):
    """-> [(name, target_path, base_path|None)] from objdiff.json, plus the
    orphan target-obj set (files in obj/ that no unit claims)."""
    d = json.load(open(os.path.join(wt, 'objdiff.json')))
    units, claimed = [], set()
    for u in d['units']:
        tp = os.path.join(wt, u['target_path'])
        bp = os.path.join(wt, u['base_path']) if u.get('base_path') else None
        claimed.add(os.path.abspath(tp))
        units.append((u['name'], tp, bp))
    root = os.path.join(wt, 'build/45410914/obj')
    orphans = [p for p in glob.glob(os.path.join(root, '**', '*.obj'),
                                    recursive=True)
               if os.path.abspath(p) not in claimed]
    return units, orphans, root


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('worktree')
    ap.add_argument('--json')
    ap.add_argument('--top', type=int, default=45)
    ap.add_argument('--orphans', action='store_true',
                    help='also scan orphan objs (slow, diagnostic only)')
    a = ap.parse_args()
    wt = a.worktree

    img = G.Image(os.path.join(wt, 'orig/45410914/band.exe'))
    _tmap, rev = G.load_target_map(wt)
    tellname = G.build_tellname(rev)

    pct = {}
    for u in json.load(open(os.path.join(wt,
                                         'build/45410914/report.json')))['units']:
        for f in (u.get('functions') or []):
            pct[(u['name'], f['name'])] = f['match_percent_normalized']

    units, orphans, root = load_units(wt)
    auto = [p for p in orphans if os.path.basename(p).startswith('auto_')]
    stale = [p for p in orphans if not os.path.basename(p).startswith('auto_')]

    tu_rows, fn_rows = [], []
    strings_of = collections.defaultdict(set)

    for name, tp, bp in units:
        tgt = G.scan_obj(tp, img, tellname)
        if not tgt:
            continue
        bsz_raw = {}
        base_raw = G.scan_obj_base(bp, bsz_raw) if bp else None
        bsizes = {norm(k): v for k, v in bsz_raw.items()}
        base = None if base_raw is None else {norm(k): v
                                             for k, v in base_raw.items()}
        tn = tb = named_excess = 0
        for sym, (size, sites, _ord) in tgt.items():
            ls = [s for s in sites if s['form'] == 'LOCAL_STATIC']
            if not ls:
                continue
            tn += len(ls)
            strings_of[norm(sym)].add(tuple(s['string'] for s in ls
                                            if s['string']))
            bl = (base or {}).get(norm(sym)) or []
            tb += len(bl)
            excess = len(ls) - len(bl)
            if excess <= 0:
                continue
            anonymous = bool(ANON_RE.match(sym))
            p = pct.get((name, sym))
            labels = []
            if base is None:
                labels.append('TARGET_ONLY_PIN')
            elif norm(sym) not in bsizes:
                labels.append('UNPAIRED_BASE')
            if anonymous:
                labels.append('ANON_TARGET')
            elif bp:
                named_excess += excess
            if p is None:
                labels.append('NO_REPORT_PAIRING')
            if STL_RE.search(sym):
                labels.append('MISPAIR_STL')
            bsz = bsizes.get(norm(sym))
            if bsz and (size > 3 * bsz or bsz > 3 * size):
                labels.append('MISPAIR_SIZE')
            if any(s['string'] is None for s in ls):
                labels.append('NO_STRING')
            # ★ laneAY-B, measured: patch_gen sets form=LOCAL_STATIC on
            # `guard_va is not None` ALONE, and its target-side guard test is
            # "some .data VA that is both loaded and stored in the window" --
            # which any ordinary FILE-SCOPE static satisfies (`sResources`,
            # `sCharClipTypes`, ...). The base-side scanner uses the exact
            # symbol-name test (`??_B`/`$S`/`?$S`), so the two disagree on
            # byte-identical code and the row reads as pure excess.
            # A REAL function-local static always resolves BOTH a guard BIT
            # (sequential across the group) and a static_va (marching down by
            # 4). Requiring both cleanly separated all 9 rows in a hand audit:
            # CharBoneDir::Init(5), UIEventMgr::Init(2), Part
            # InitParticleSystem(1), GemManager ctor(3) and BeatMaster
            # ::CheckBeat(1) all print bit=None static=None and are FALSE
            # POSITIVES -- which is exactly why they sat at 100%/99.99%.
            if any(s['guard_bit'] is None or s['static_va'] is None
                   for s in ls):
                labels.append('WEAK_GUARD')
            fn_rows.append({
                'unit': name, 'sym': sym, 'pct': p, 'tgt': len(ls),
                'base': len(bl), 'excess': excess, 'size': size,
                'paired': bp is not None, 'anon': anonymous, 'labels': labels,
                'statics': [{'kind': s['kind'], 'arity': s.get('arity'),
                             'string': s['string'], 'off': s['off'],
                             'guard_va': s['guard_va'],
                             'guard_bit': s['guard_bit'],
                             'static_va': s['static_va']} for s in ls],
            })
        if tn:
            tu_rows.append({'unit': name, 'tgt': tn, 'base': tb,
                            'excess': tn - tb, 'paired': bp is not None,
                            'named_excess': named_excess})

    xobj = {n for n, seqs in strings_of.items() if len(seqs) > 1}
    for r in fn_rows:
        if norm(r['sym']) in xobj:
            r['labels'].append('MISPAIR_XOBJ')

    print('== 0) UNIVERSE (from objdiff.json, NOT a glob of obj/) ==')
    print('   units in objdiff.json            : %d' % len(units))
    print('     ...with a compiled base obj    : %d  <- the only editable set'
          % sum(1 for _n, _t, b in units if b))
    print('     ...target-only pins            : %d'
          % sum(1 for _n, _t, b in units if not b))
    print('   orphan objs in build/45410914/obj: %d' % len(orphans))
    print('     auto_* dtk carve (no source)   : %d' % len(auto))
    print('     ★ STALE (dead splits.txt gen)  : %d' % len(stale))
    if stale:
        print('       %s%s' % (', '.join(sorted(
            os.path.relpath(p, root)[:-4] for p in stale)[:12]),
            ' ...' if len(stale) > 12 else ''))

    paired = [t for t in tu_rows if t['paired']]
    tonly = [t for t in tu_rows if not t['paired']]
    paired_pos = [t for t in paired if t['excess'] > 0]
    print('\n== A) TU-LEVEL AGGREGATE (guard-verified, pairing-free) ==')
    print('   compiled units with target-side local statics : %d' % len(paired))
    print('   ...with NET EXCESS                            : %d  (%d statics)'
          % (len(paired_pos), sum(t['excess'] for t in paired_pos)))
    print('   target-only pins with excess (NOT EDITABLE)   : %d  (%d statics)'
          % (len([t for t in tonly if t['excess'] > 0]),
             sum(t['excess'] for t in tonly if t['excess'] > 0)))

    res = collections.Counter()
    for r in fn_rows:
        k = ('paired' if r['paired'] else 'tonly',
             'anon' if r['anon'] else 'named')
        res[k + ('t',)] += len(r['statics'])
        res[k + ('n',)] += sum(1 for s in r['statics'] if s['string'] is None)
    print('\n   string resolution (excess rows only):')
    for k in sorted({(x, y) for x, y, _ in res}):
        t, n = res[k + ('t',)], res[k + ('n',)]
        print('     %-7s %-6s %5d statics, %4d unresolved (%.1f%%)'
              % (k[0], k[1], t, n, 100.0 * n / max(t, 1)))

    rf = [r for r in fn_rows if r['paired']]
    print('\n== B) PER-FUNCTION, compiled units only ==')
    print('   functions with excess : %d across %d units, %d excess statics'
          % (len(rf), len({r['unit'] for r in rf}),
             sum(r['excess'] for r in rf)))
    for k, v in collections.Counter(l for r in rf
                                    for l in r['labels']).most_common():
        print('     %-20s %d' % (k, v))

    bad = {'MISPAIR_STL', 'MISPAIR_XOBJ', 'MISPAIR_SIZE', 'NO_STRING',
           'WEAK_GUARD'}
    clean = [r for r in rf if not (bad & set(r['labels']))]
    killed = [r for r in rf if (bad & set(r['labels']))]
    named = [r for r in clean if not r['anon']]
    print('\n== C) PRECISION FILTER (drop MISPAIR_*, NO_STRING, WEAK_GUARD) ==')
    print('   killed %d rows (%d excess statics)'
          % (len(killed), sum(r['excess'] for r in killed)))
    print('   surviving : %d functions / %d units / %d excess statics'
          % (len(clean), len({r['unit'] for r in clean}),
             sum(r['excess'] for r in clean)))
    print('   ...NAMED (directly editable): %d functions / %d units / %d excess'
          % (len(named), len({r['unit'] for r in named}),
             sum(r['excess'] for r in named)))

    print('\n== RANKED ACTIONABLE UNITS ==')
    per_tu, per_fns = collections.Counter(), collections.Counter()
    for r in named:
        per_tu[r['unit']] += r['excess']
        per_fns[r['unit']] += 1
    shown = 0
    for u, n in per_tu.most_common():
        stem = os.path.basename(u)
        mark = '[AT]' if stem in LANE_AT_OWNED else \
               ('[AX]' if stem in LANE_AX_INFLIGHT else '    ')
        print('   %s %4d statics  %2d fns  %s' % (mark, n, per_fns[u], u))
        shown += 1
        if shown >= a.top:
            break
    tot = sum(n for u, n in per_tu.items())
    print('\n   TOTAL NAMED-ACTIONABLE: %d statics across %d units'
          % (tot, len(per_tu)))

    if a.json:
        json.dump({'tu': tu_rows, 'fn': fn_rows,
                   'orphans': sorted(os.path.relpath(p, root)[:-4]
                                     for p in stale)},
                  open(a.json, 'w'), indent=1)


if __name__ == '__main__':
    main()
