#!/usr/bin/env python3
"""Find map entries that denote the SAME function as one of our compiled
symbols but are spelled with a different MANGLING (e.g. missing MSVC
back-reference compression, because the name was generated by our own tooling
rather than emitted by the compiler).

objdiff pairs target<->base BY NAME, so such an entry can never pair and the
function reads 0% forever, no matter how correct the body is.

Comparison is done on the DEMANGLED form via llvm-undname (a real MSVC
demangler) rather than by hand-parsing back-references.
"""
import glob, json, os, re, struct, subprocess, sys, bisect
from collections import defaultdict
from pathlib import Path

ROOT = Path(os.environ.get("RESIDUE_ROOT", "/home/free/tmp/wt-residue"))

def parse_defined(data):
    if len(data) < 20: return []
    so = struct.unpack_from("<I", data, 8)[0]; n = struct.unpack_from("<I", data, 12)[0]
    if not so or not n: return []
    st = so + n * 18; out = []; i = 0
    while i < n:
        eo = so + i * 18
        if eo + 18 > len(data): break
        nb = data[eo:eo+8]
        if nb[:4] == b"\x00\x00\x00\x00":
            o = struct.unpack_from("<I", nb, 4)[0]; ao = st + o
            try: name = data[ao:data.index(b"\x00", ao)].decode("ascii", "replace")
            except ValueError: name = ""
        else: name = nb.split(b"\x00")[0].decode("ascii", "replace")
        secn = struct.unpack_from("<h", data, eo+12)[0]; aux = data[eo+17]
        if secn > 0: out.append(name)
        i += 1 + aux
    return out

def demangle(names):
    """bulk llvm-undname; returns dict name -> demangled (or None)."""
    out = {}
    CH = 4000
    lst = list(names)
    for i in range(0, len(lst), CH):
        chunk = lst[i:i+CH]
        try:
            p = subprocess.run(["llvm-undname"], input="\n".join(chunk),
                               capture_output=True, text=True, timeout=180)
        except Exception:
            continue
        # llvm-undname emits a RECORD per input: the echoed mangled name, then
        # the demangled form (which may itself wrap onto several lines), then a
        # blank line. Drive the parse off the known input order rather than a
        # fixed stride, so a multi-line demangling cannot desync the whole run.
        lines = p.stdout.split("\n")
        li = 0
        for c in chunk:
            while li < len(lines) and lines[li].strip() != c:
                li += 1
            if li >= len(lines):
                break                      # desync: leave the rest unresolved
            li += 1
            buf = []
            while li < len(lines) and lines[li].strip() != "":
                buf.append(lines[li].strip())
                li += 1
            r = " ".join(buf).strip()
            out[c] = None if (not r or r.startswith("error:")) else r
    return out

defined = set(); sym_obj = {}
for f in glob.glob(str(ROOT/"build/45410914/src/**/*.obj"), recursive=True):
    try: d = parse_defined(open(f, "rb").read())
    except Exception: continue
    for s in d:
        defined.add(s); sym_obj.setdefault(s, f)

ANON = re.compile(r'\?A0x[0-9a-f]+')
def norm(n): return ANON.sub('?A0xANON', n)
ndefined = {norm(x) for x in defined}

txt = (ROOT/"config/45410914/splits.txt").read_text()
cur = None; unit_ranges = []
for line in txt.splitlines():
    if line and not line[0].isspace() and line.rstrip().endswith(":") and line.rstrip()[:-1].endswith((".cpp", ".c")):
        cur = line.rstrip()[:-1]; continue
    mt = re.search(r"\.text\s+start:0x([0-9A-Fa-f]+)\s+end:0x([0-9A-Fa-f]+)", line)
    if mt and cur: unit_ranges.append((int(mt.group(1),16), int(mt.group(2),16), cur))
unit_ranges.sort(); starts=[r[0] for r in unit_ranges]
def unit_of(a):
    i = bisect.bisect_right(starts, a) - 1
    if i >= 0 and unit_ranges[i][0] <= a < unit_ranges[i][1]: return unit_ranges[i][2]
    return None

raw = json.loads((ROOT/"scripts/target_symbol_map.json").read_text())
unpaired = {}
for k, v in raw.items():
    if not k.lower().startswith("0x"): continue
    try: a = int(k.lower().removeprefix("0x"), 16)
    except ValueError: continue
    if norm(v) in ndefined: continue
    unpaired[v] = a

print(f"demangling {len(unpaired)} unpaired map names + {len(defined)} of ours...", file=sys.stderr)
dm_map = demangle(unpaired.keys())
dm_our = demangle(defined)

WS = re.compile(r'\s+')
def canon(s):
    if not s: return None
    s = s.replace("__cdecl ", "").replace("__thiscall ", "")
    s = s.replace("public: ", "").replace("private: ", "").replace("protected: ", "")
    s = s.replace("virtual ", "").replace("static ", "")
    s = WS.sub(" ", s).strip()
    return s

our_by_canon = defaultdict(list)
for s in defined:
    c = canon(dm_our.get(s))
    if c: our_by_canon[norm(c)].append(s)

hits = []
for v, a in unpaired.items():
    c = canon(dm_map.get(v))
    if not c: continue
    cands = our_by_canon.get(norm(c), [])
    if len(cands) != 1: continue
    hits.append({"addr": f"0x{a:08X}", "unit": unit_of(a), "map_name": v,
                 "our_name": cands[0], "demangled": c,
                 "obj": os.path.relpath(sym_obj.get(cands[0], ""), ROOT)})

pin = [h for h in hits if h["unit"]]
print(f"same-function / different-mangling: {len(hits)} ({len(pin)} inside a pinned unit)")
json.dump(hits, open(ROOT/"scripts/_mangle_backref.json", "w"), indent=1)
by = defaultdict(int)
for h in pin: by[h["unit"]] += 1
for u, n in sorted(by.items(), key=lambda z: -z[1])[:30]:
    print(f"  {n:>3}  {u}")
