#!/usr/bin/env python3
"""
map_verify.py — audit `scripts/target_symbol_map.json` entries against static
evidence, per pinned unit or tree-wide.

Why
---
Map entries generated by `tools/gen_game_target_map.py` (from the BinDiff /
rb3-Wii `unified_id_rb3wii.json` oracle) are systematically MIS-PAIRED for
small generic functions (wave-20 findings: TrackPanel `?PushCrowdReaction`
mapped onto an unrelated vtable-dispatch routine; RockCentral's mid-fuzzy band
is ~21/23 Ghidra-verified mis-pairs of trivial getters onto guard-word
thunks). Because the pre-compile `obj_target_symbol_renamer` burns the mapped
name onto the target obj's `fn_<addr>` symbol, objdiff then silently compares
our (often correct) source against the WRONG retail function — producing
fake near-zero/mid-fuzzy scores that waste porting effort.

What it checks (static evidence, no Ghidra round-trips)
-------------------------------------------------------
For every named map entry whose address falls inside a pinned unit's `.text`
ranges, cross-check the retail function at that address (via the dtk asm
`build/45410914/asm/<unit>.s` + raw bytes from `orig/45410914/band.exe`)
against our compiled obj's same-named COMDAT:

  (a) size ratio            target `.fn` size vs our COMDAT section size
  (b) referenced strings    target: read bytes at `addi ..,lbl_X+off@l`
                            addresses; base: raw bytes of `??_C@` reloc
                            targets' sections. Disjoint non-empty sets are
                            near-proof of a mis-pair; any intersection is
                            strong pro-pair evidence.
  (c) float constants       target: 4/8-byte reads at `lfs/lfd` reloc
                            addresses; base: bits from `__real@<hex>` names.
  (d) callee identity       target `bl` target addresses mapped back through
                            target_symbol_map vs base REL24 callee names.
  (e) call-count sanity     target `bl`/tail-`b` count vs base REL24 count.
  (f) opcode-shape          primary/extended-opcode multiset similarity
                            between target words and base COMDAT words
                            (catches 8-byte getters mapped to 32-byte
                            guard-word clears: zero consts either side, but
                            totally different instruction mix).

A function that report.json already scores match_percent_normalized==100 is
byte-proven and reported OK regardless of the heuristics.

Verdicts: OK / SUSPECT / MISPAIR (+ NO_BASE when our obj has no such COMDAT,
BAD_ADDR when the address is not a `.fn` start in the unit's asm). MISPAIR
requires strong negative evidence AND no positive const/callee evidence —
treat SUSPECT as "verify in Ghidra before trusting", MISPAIR as "verified
wrong by content, fix the map".

Usage
-----
  python3 scripts/map_verify.py --unit band3/bandtrack/TrackPanel   # one unit
  python3 scripts/map_verify.py --unit RockCentral
  python3 scripts/map_verify.py --all                               # tree-wide
  python3 scripts/map_verify.py --all --csv OUT.csv --summary
Options: --csv FILE (write per-entry CSV), --summary (per-unit rollup only),
--verbose (evidence detail per entry).
"""
import argparse
import bisect
import csv
import glob
import json
import os
import re
import struct
import sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BAND = os.path.join(ROOT, "orig/45410914/band.exe")
SPLITS = os.path.join(ROOT, "config/45410914/splits.txt")
TMAP = os.path.join(ROOT, "scripts/target_symbol_map.json")
REPORT = os.path.join(ROOT, "build/45410914/report.json")
ASMDIR = os.path.join(ROOT, "build/45410914/asm")
SRCOBJ = os.path.join(ROOT, "build/45410914/src")

IMAGE_REL_PPC_REL24 = 0x0006
IMAGE_REL_PPC_REFHI = 0x0010
IMAGE_REL_PPC_REFLO = 0x0011


# ---------------------------------------------------------------- band.exe --
class Image:
    """vaddr -> raw-bytes reader over every section of band.exe."""

    def __init__(self, path):
        self.d = open(path, "rb").read()
        d = self.d
        peoff = struct.unpack("<I", d[0x3C:0x40])[0]
        coff = peoff + 4
        _, nsec, _, _, _, optsz, _ = struct.unpack("<HHIIIHH", d[coff:coff + 20])
        opt = coff + 20
        self.base = struct.unpack("<I", d[opt + 28:opt + 32])[0]
        sechdr = opt + optsz
        self.secs = []  # (va, va_end_raw, rawptr)
        for i in range(nsec):
            o = sechdr + i * 40
            va = struct.unpack("<I", d[o + 12:o + 16])[0] + self.base
            rawsz = struct.unpack("<I", d[o + 16:o + 20])[0]
            rawptr = struct.unpack("<I", d[o + 20:o + 24])[0]
            if rawsz:
                self.secs.append((va, va + rawsz, rawptr))
        self.secs.sort()
        self.starts = [s[0] for s in self.secs]

    def read(self, va, n):
        i = bisect.bisect_right(self.starts, va) - 1
        if i < 0:
            return None
        s, e, raw = self.secs[i]
        if va < s or va + n > e:
            return None
        off = raw + (va - s)
        return self.d[off:off + n]

    def cstring(self, va, maxlen=256):
        b = self.read(va, maxlen)
        if not b:
            return None
        end = b.find(b"\x00")
        if end < 3:  # too short to be discriminating
            return None
        s = b[:end]
        if all(0x20 <= c < 0x7F or c in (9, 10, 13) for c in s):
            return s.decode("latin1")
        return None


# ------------------------------------------------------------- our .obj side --
def parse_obj(path):
    """Return name -> {size, calls[], strs set, flts set, words[]} for every
    function-typed symbol in an MSVC COFF obj (each function = own COMDAT)."""
    d = open(path, "rb").read()
    _, nsec, _, symptr, nsym, optsz, _ = struct.unpack("<HHIIIHH", d[:20])
    strtab = symptr + nsym * 18

    names = {}  # sym index -> name

    def symname(idx):
        if idx in names:
            return names[idx]
        off = symptr + idx * 18
        rec = d[off:off + 8]
        if rec[:4] == b"\x00\x00\x00\x00":
            o = struct.unpack("<I", rec[4:8])[0]
            e = d.index(b"\x00", strtab + o)
            nm = d[strtab + o:e].decode("latin1")
        else:
            nm = rec.rstrip(b"\x00").decode("latin1")
        names[idx] = nm
        return nm

    sec_fns = {}    # section -> [(val, name)] function-typed symbols
    sym_sec = {}    # any symbol name -> section (for ??_C string payload reads)
    i = 0
    while i < nsym:
        off = symptr + i * 18
        val, sec, typ, cls, naux = struct.unpack("<IhHBB", d[off + 8:off + 18])
        if sec > 0 and cls in (2, 3):
            nm = symname(i)
            sym_sec.setdefault(nm, sec)
            # NOTE: EH-carrying functions sit at val=8 inside their COMDAT
            # (X360 MSVC prepends an 8-byte EH thunk stub) — accept any val.
            if (typ >> 4) == 2:
                sec_fns.setdefault(sec, []).append((val, nm))
        i += 1 + naux

    sechdr = 20 + optsz

    def sec_raw(sec):
        o = sechdr + (sec - 1) * 40
        rawsz = struct.unpack("<I", d[o + 16:o + 20])[0]
        rawptr = struct.unpack("<I", d[o + 20:o + 24])[0]
        return rawsz, rawptr

    out = {}
    for sec, fnlist in sec_fns.items():
        o = sechdr + (sec - 1) * 40
        rawsz, rawptr, relptr, _, nrel = struct.unpack("<IIIIH", d[o + 16:o + 34])
        fnlist.sort()
        for j, (val, fname) in enumerate(fnlist):
            end = fnlist[j + 1][0] if j + 1 < len(fnlist) else rawsz
            calls, strs, flts = [], set(), set()
            for r in range(nrel):
                ro = relptr + r * 10
                va, si, rt = struct.unpack("<IIH", d[ro:ro + 10])
                if not val <= va < end:
                    continue
                nm = symname(si)
                if nm == "@comp.id":
                    continue
                if rt == IMAGE_REL_PPC_REL24:
                    calls.append(nm)
                elif rt in (IMAGE_REL_PPC_REFHI, IMAGE_REL_PPC_REFLO):
                    if nm.startswith("??_C@"):
                        ssec = sym_sec.get(nm)
                        if ssec:
                            ssz, sptr = sec_raw(ssec)
                            payload = d[sptr:sptr + ssz]
                            e = payload.find(b"\x00")
                            if e >= 3 and all(
                                    0x20 <= c < 0x7F or c in (9, 10, 13)
                                    for c in payload[:e]):
                                strs.add(payload[:e].decode("latin1"))
                    elif nm.startswith("__real@"):
                        flts.add(nm[7:].lower())
            words = [struct.unpack(">I", d[rawptr + k:rawptr + k + 4])[0]
                     for k in range(val, end - (end - val) % 4, 4)]
            out.setdefault(fname, {"size": end - val, "calls": calls,
                                   "strs": strs, "flts": flts, "words": words})
    return out


# ------------------------------------------------------------ target .s side --
FN_HDR = re.compile(r"^# \.text:0x[0-9A-Fa-f]+ \| (0x[0-9A-Fa-f]+) \| size: (0x[0-9A-Fa-f]+)")
FN_BEGIN = re.compile(r"^\.fn (\w+)")
FN_END = re.compile(r"^\.endfn (\w+)")
INSN = re.compile(r"^/\* ([0-9A-F]{8}) [0-9A-F]{8}\s+"
                  r"([0-9A-F]{2}) ([0-9A-F]{2}) ([0-9A-F]{2}) ([0-9A-F]{2}) \*/\t(\S+)(.*)")
DREF = re.compile(r"(?:lbl|fn|jumptable)_([0-9A-Fa-f]{8})(?:\+0x([0-9A-Fa-f]+))?@(ha|l|sda21)")
BRTGT = re.compile(r"^\s*([^\s,]+)\s*$")


def parse_unit_asm(path):
    """Return addr -> {size, calls[names], str_addrs, flt_reads, words[]}."""
    fns = {}
    cur = None
    pend_addr = pend_size = None
    for line in open(path, errors="replace"):
        m = FN_HDR.match(line)
        if m:
            pend_addr, pend_size = int(m.group(1), 16), int(m.group(2), 16)
            continue
        m = FN_BEGIN.match(line)
        if m:
            # For units with discontiguous .text ranges, dtk's header comment
            # carries a synthetic contiguous address; the TRUE virtual address
            # is embedded in the label name (fn_XXXXXXXX). Prefer it.
            am = re.match(r"(?:fn|lbl)_([0-9A-Fa-f]{8})$", m.group(1))
            addr = int(am.group(1), 16) if am else pend_addr
            cur = {"addr": addr, "size": pend_size, "calls": [],
                   "str_addrs": set(), "flt_reads": [], "words": []}
            if addr is not None:
                fns[addr] = cur
            continue
        if FN_END.match(line):
            cur = None
            continue
        if cur is None:
            continue
        m = INSN.match(line)
        if not m:
            continue
        word = int(m.group(2) + m.group(3) + m.group(4) + m.group(5), 16)
        mnem = m.group(6)
        rest = m.group(7)
        cur["words"].append(word)
        if mnem in ("bl", "b"):
            tgt = rest.strip()
            if not tgt.startswith(".L_"):
                if mnem == "bl" or not cur["words"] or True:
                    # tail-b to a symbol counts as a call-site for parity with
                    # base REL24 relocs (both sides emit one reloc per site)
                    cur["calls"].append(tgt)
            continue
        dm = DREF.search(rest)
        if dm and dm.group(3) in ("l", "sda21"):
            va = int(dm.group(1), 16) + (int(dm.group(2), 16) if dm.group(2) else 0)
            if mnem == "addi":
                cur["str_addrs"].add(va)
            elif mnem in ("lfs", "lfsx"):
                cur["flt_reads"].append((va, 4))
            elif mnem in ("lfd", "lfdx"):
                cur["flt_reads"].append((va, 8))
    return fns


# --------------------------------------------------------------- comparison --
def opc_multiset(words):
    out = Counter()
    for w in words:
        op = w >> 26
        if op in (19, 31, 59, 63):
            out[(op, (w >> 1) & 0x3FF)] += 1
        else:
            out[(op,)] += 1
    return out


def opc_similarity(a, b):
    if not a or not b:
        return None
    inter = sum((a & b).values())
    return inter / max(sum(a.values()), sum(b.values()))


def target_consts(fn, img):
    strs, flts = set(), set()
    for va in fn["str_addrs"]:
        s = img.cstring(va)
        if s:
            strs.add(s)
    for va, n in fn["flt_reads"]:
        b = img.read(va, n)
        if b:
            flts.add(b.hex())
    return strs, flts


def state(tset, bset):
    if tset and bset:
        return ("MATCH", len(tset & bset)) if tset & bset else ("DISJOINT", 0)
    if bset:
        return ("ONLY_BASE", 0)
    if tset:
        return ("ONLY_TGT", 0)
    return ("NONE", 0)


def verify_entry(addr, name, tfn, bfn, img, addr2name, matched100):
    ev = {}
    if tfn is None:
        return "BAD_ADDR", ev
    if bfn is None:
        return "NO_BASE", ev

    tsz, bsz = tfn["size"], bfn["size"]
    ratio = min(tsz, bsz) / max(tsz, bsz) if max(tsz, bsz) else 0.0
    ev["tsz"], ev["bsz"], ev["ratio"] = tsz, bsz, round(ratio, 2)

    tstrs, tflts = target_consts(tfn, img)
    sst, sinter = state(tstrs, bfn["strs"])
    fst, finter = state(tflts, bfn["flts"])
    ev["str"], ev["str_n"] = sst, sinter
    ev["flt"], ev["flt_n"] = fst, finter
    ev["tstrs"], ev["bstrs"] = sorted(tstrs)[:4], sorted(bfn["strs"])[:4]

    # callee identity through the map: target bl fn_XXXX -> mapped name
    tcallees = set()
    for c in tfn["calls"]:
        m = re.match(r"(?:fn|lbl)_([0-9A-Fa-f]{8})", c)
        if m:
            mapped = addr2name.get(int(m.group(1), 16))
            if mapped:
                tcallees.add(mapped)
        elif not c.startswith("__"):
            tcallees.add(c)
    bcallees = {c for c in bfn["calls"] if not c.startswith(("__save", "__rest"))}
    cst, cinter = state(tcallees, bcallees)
    ev["callee"], ev["callee_n"] = cst, cinter

    tcalls, bcalls = len(tfn["calls"]), len(bfn["calls"])
    call_ok = abs(tcalls - bcalls) <= max(2, 0.5 * max(tcalls, bcalls))
    ev["tcalls"], ev["bcalls"] = tcalls, bcalls

    sim = opc_similarity(opc_multiset(tfn["words"]), opc_multiset(bfn["words"]))
    ev["opc_sim"] = round(sim, 2) if sim is not None else None

    if matched100:
        ev["proof"] = "match_percent_normalized==100"
        return "OK", ev

    neg = pos = 0
    if sst == "DISJOINT":
        neg += 3
    elif sst in ("ONLY_BASE", "ONLY_TGT"):
        neg += 1
    elif sst == "MATCH":
        pos += 3
    if fst == "DISJOINT":
        neg += 2
    elif fst == "MATCH":
        pos += 2 if set(bfn["flts"]) & tflts - {"00000000"} else 1
    elif fst == "ONLY_BASE" and any(f != "00000000" for f in bfn["flts"]) \
            and not tfn["flt_reads"]:
        neg += 2  # base provably loads fp consts; target has zero fp loads
    elif fst in ("ONLY_BASE", "ONLY_TGT"):
        neg += 1
    if cst == "DISJOINT":
        neg += 2
    elif cst == "MATCH":
        pos += 2
    if ratio < 0.5:
        neg += 2
    elif ratio < 0.75:
        neg += 1
    else:
        pos += 1
    if call_ok:
        pos += 1
    else:
        neg += 1
    if sim is not None:
        if sim >= 0.7:
            pos += 1
        elif sim < 0.35:
            neg += 2
        elif sim < 0.55:
            neg += 1
    ev["neg"], ev["pos"] = neg, pos

    # string identity trumps callee overlap: callees are often shared helpers
    # (Symbol ctor, IsConnected, ...) while referenced string CONTENT is a
    # near-unique fingerprint of the function body.
    strong_pos = (sst == "MATCH") or (cst == "MATCH" and sst != "DISJOINT")
    if neg >= 4 and neg > pos and not strong_pos:
        return "MISPAIR", ev
    if neg >= 2 and neg > pos:
        return "SUSPECT", ev
    return "OK", ev


# ----------------------------------------------------- cross-obj fallback --
_SYM_INDEX = None          # symname -> obj path (built lazily, once)
_OBJ_CACHE = {}            # obj path -> parse_obj() result


def obj_funcs(path):
    if path not in _OBJ_CACHE:
        try:
            _OBJ_CACHE[path] = parse_obj(path)
        except Exception:
            _OBJ_CACHE[path] = {}
    return _OBJ_CACHE[path]


def global_sym_index():
    """symname -> some obj defining it (COMDATs are identical everywhere)."""
    global _SYM_INDEX
    if _SYM_INDEX is not None:
        return _SYM_INDEX
    _SYM_INDEX = {}
    for p in glob.glob(os.path.join(SRCOBJ, "**", "*.obj"), recursive=True):
        try:
            d = open(p, "rb").read()
        except OSError:
            continue
        if len(d) < 20:
            continue
        _, _, _, symptr, nsym, _, _ = struct.unpack("<HHIIIHH", d[:20])
        strtab = symptr + nsym * 18
        i = 0
        while i < nsym:
            off = symptr + i * 18
            val, sec, typ, cls, naux = struct.unpack("<IhHBB", d[off + 8:off + 18])
            if sec > 0 and cls in (2, 3) and (typ >> 4) == 2:
                rec = d[off:off + 8]
                if rec[:4] == b"\x00\x00\x00\x00":
                    o = struct.unpack("<I", rec[4:8])[0]
                    e = d.index(b"\x00", strtab + o)
                    nm = d[strtab + o:e].decode("latin1")
                else:
                    nm = rec.rstrip(b"\x00").decode("latin1")
                _SYM_INDEX.setdefault(nm, p)
            i += 1 + naux
    return _SYM_INDEX


EH_AUX = re.compile(r"^__(unwind|ehfuncinfo|unwindfunclet|tryblocktable|"
                    r"catchsym|ip2state|catch)\$?")


# ------------------------------------------------------------------ driver --
def load_splits():
    """splits key (path, no .cpp) -> sorted list of (.text start, end)."""
    units = {}
    cur = None
    for line in open(SPLITS):
        s = line.rstrip("\n")
        m = re.match(r"^([\w./\-]+)\.cpp:\s*$", s)
        if m:
            cur = m.group(1)
            continue
        if s and not s[0] in " \t":
            cur = None
            continue
        m = re.match(r"\s+\.text\s+start:0x([0-9A-Fa-f]+) end:0x([0-9A-Fa-f]+)", s)
        if m and cur:
            units.setdefault(cur, []).append(
                (int(m.group(1), 16), int(m.group(2), 16)))
    return {k: sorted(v) for k, v in units.items()}


def find_obj(unit):
    """Resolve a splits unit path to our compiled obj."""
    stem = unit.split("/")[-1]
    cands = glob.glob(os.path.join(SRCOBJ, "**", stem + ".obj"), recursive=True)
    if not cands:
        return None
    if len(cands) == 1:
        return cands[0]
    # prefer the candidate whose path suffix matches the unit dir
    for c in cands:
        if c.endswith(unit + ".obj"):
            return c
    return cands[0]


def load_report_matches():
    """(report-unit-name, fn-name) -> match_percent_normalized."""
    out = {}
    if not os.path.exists(REPORT):
        return out
    r = json.load(open(REPORT))
    for u in r["units"]:
        for f in u.get("functions", []):
            out[(u["name"], f["name"])] = f["match_percent_normalized"]
    return out


def audit_unit(unit, ranges, tmap_by_addr, img, mp, rows, verbose=False):
    asm = os.path.join(ASMDIR, unit + ".s")
    if not os.path.exists(asm):
        return None
    objp = find_obj(unit)
    if not objp:
        return None
    entries = [(a, n) for a, n in tmap_by_addr.items()
               if any(s <= a < e for s, e in ranges)]
    if not entries:
        return {"unit": unit, "entries": 0}
    tfns = parse_unit_asm(asm)
    bfns = obj_funcs(objp)
    rep_unit = "default/" + unit
    counts = Counter()
    for addr, name in sorted(entries):
        if EH_AUX.match(name):
            counts["EH_AUX"] += 1
            continue
        m100 = mp.get((rep_unit, name), 0.0) >= 100.0
        bfn = bfns.get(name)
        foreign = ""
        if bfn is None:
            # name not defined by this unit's obj (a mis-pair red flag on its
            # own for game classes) — verify against any obj defining it
            other = global_sym_index().get(name)
            if other:
                bfn = obj_funcs(other).get(name)
                foreign = os.path.relpath(other, SRCOBJ)
        verdict, ev = verify_entry(addr, name, tfns.get(addr),
                                   bfn, img, tmap_by_addr, m100)
        if foreign:
            ev["foreign"] = foreign
        counts[verdict] += 1
        rows.append({
            "unit": unit, "addr": f"0x{addr:08X}", "name": name,
            "verdict": verdict,
            "mp": round(mp.get((rep_unit, name), -1.0), 1),
            "tsz": ev.get("tsz", ""), "bsz": ev.get("bsz", ""),
            "ratio": ev.get("ratio", ""),
            "tcalls": ev.get("tcalls", ""), "bcalls": ev.get("bcalls", ""),
            "str": ev.get("str", ""), "flt": ev.get("flt", ""),
            "callee": ev.get("callee", ""), "opc_sim": ev.get("opc_sim", ""),
            "neg": ev.get("neg", ""), "pos": ev.get("pos", ""),
            "foreign": ev.get("foreign", ""),
            "evidence": ("tstrs=%r bstrs=%r" % (ev.get("tstrs"), ev.get("bstrs"))
                         if verbose and (ev.get("tstrs") or ev.get("bstrs")) else ""),
        })
    return {"unit": unit, "entries": len(entries), **counts}


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--unit", help="unit path as in splits.txt, without .cpp "
                    "(e.g. band3/bandtrack/TrackPanel or RockCentral)")
    ap.add_argument("--all", action="store_true", help="audit every pinned unit")
    ap.add_argument("--csv", help="write per-entry CSV here")
    ap.add_argument("--summary", action="store_true",
                    help="print only the per-unit rollup")
    ap.add_argument("--verbose", action="store_true",
                    help="include string evidence in output rows")
    args = ap.parse_args()
    if not args.unit and not args.all:
        ap.error("need --unit or --all")

    tmap_by_addr = {}
    for k, v in json.load(open(TMAP)).items():
        if k[:2].lower() == "0x":
            tmap_by_addr[int(k, 16)] = v

    splits = load_splits()
    img = Image(BAND)
    mp = load_report_matches()

    units = sorted(splits) if args.all else [args.unit]
    rows = []
    summaries = []
    for u in units:
        if u not in splits:
            print(f"ERROR: unit {u!r} not in splits.txt", file=sys.stderr)
            sys.exit(1) if not args.all else None
            continue
        s = audit_unit(u, splits[u], tmap_by_addr, img, mp, rows,
                       verbose=args.verbose)
        if s and s.get("entries"):
            summaries.append(s)

    cols = ["unit", "addr", "name", "verdict", "mp", "tsz", "bsz", "ratio",
            "tcalls", "bcalls", "str", "flt", "callee", "opc_sim",
            "neg", "pos", "foreign", "evidence"]
    if args.csv:
        with open(args.csv, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=cols)
            w.writeheader()
            w.writerows(rows)
        print(f"wrote {len(rows)} rows -> {args.csv}")

    if not args.summary:
        for r in rows:
            if r["verdict"] == "OK" and not args.verbose:
                continue
            print("  {verdict:8s} {addr} mp={mp:6} tsz={tsz:>5} bsz={bsz:>5} "
                  "str={str:9s} flt={flt:9s} callee={callee:9s} sim={opc_sim} "
                  "{name}".format(**{k: str(v) for k, v in r.items()}))
            if r["foreign"]:
                print(f"             defined in foreign obj: {r['foreign']}")
            if r["evidence"]:
                print(f"             {r['evidence']}")

    print("\nper-unit rollup (entries / OK / SUSPECT / MISPAIR / NO_BASE / "
          "BAD_ADDR / EH_AUX):")
    tot = Counter()
    keys = ("OK", "SUSPECT", "MISPAIR", "NO_BASE", "BAD_ADDR", "EH_AUX")
    for s in sorted(summaries, key=lambda x: -(x.get("MISPAIR", 0) + x.get("SUSPECT", 0))):
        for k in keys:
            tot[k] += s.get(k, 0)
        tot["entries"] += s["entries"]
        print(f"  {s['unit']:52s} {s['entries']:4d} " +
              " ".join(f"{s.get(k, 0):4d}" for k in keys))
    print(f"  {'TOTAL':52s} {tot['entries']:4d} " +
          " ".join(f"{tot[k]:4d}" for k in keys))


if __name__ == "__main__":
    main()
